spring.datasource:
  url:             jdbc:postgresql://localhost/cardb
  username:        postgres
  password:        postgres
  driverClassName: org.postgresql.Driver

spring:
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES